config/routes.rb
Rails.application.routes.draw do

  resources :board_messages
  resources :board_users
  resources :data_pages
  devise_for :accounts
  get 'ajax/index'
  get 'ajax/data'
  post 'ajax/data'

  get 'questionary_results/calc/:id', to:'questionary_results#calc'
  get 'questionary_choices/new/:id', to: 'questionary_choices#new'
  get 'questionary_items/new/:id', to: 'questionary_items#new'
  post 'questionaries/:id', to: 'questionaries#sendform'

  resources :questionary_results
  resources :questionary_choices
  resources :questionary_items
  resources :questionaries
  resources :answers
  resources :questions
  resources :mycontacts
  get 'blogs/index'
  get 'blogs', to: 'blogs#index'
  get 'blogs/:page', to: 'blogs#index'

  get 'blogs/genre/:id', to: 'blogs#genre'
  get 'blogs/genre/:id/:page', to: 'blogs#genre'

  get 'blogs/show/:id', to: 'blogs#show'

  get 'blogposts/index'
  get 'blogposts', to: 'blogposts#index'

  get 'blogposts/delete/:id', to: 'blogposts#delete'
  post 'blogposts/delete/', to: 'blogposts#delete'
  post 'blogposts/delete/:id', to: 'blogposts#delete'

  get 'blogposts/add'
  post 'blogposts/add'

  get 'blogposts/:id', to: 'blogposts#edit'
  patch 'blogposts/:id', to: 'blogposts#edit'

  get 'bloggenres/index'
  get 'bloggenres', to: 'bloggenres#index'

  get 'bloggenres/add'
  post 'bloggenres/add'

  get 'bloggenres/:id', to: 'bloggenres#edit'
  patch 'bloggenres/:id', to: 'bloggenres#edit'

  get 'blogconfigs/index'
  get 'blogconfigs', to: 'blogconfigs#index'

  get 'blogconfigs/edit'
  patch 'blogconfigs/edit'

  get 'messages/index'
  get 'messages', to:'messages#index'

  get 'messages/add'
  post 'messages/add', to: 'messages#create'

  get 'messages/edit/:id', to: 'messages#edit'
  patch 'messages/edit/:id', to: 'messages#update'

  get 'messages/delete/:id', to: 'messages#delete'
  get 'messages/:id', to: 'messages#show'

  get 'cards/index'
  get 'cards', to: 'cards#index'
  get 'cards/add'
  post 'cards/add'
  get 'cards/:id', to: 'cards#show'
  get 'cards/edit/:id', to: 'cards#edit'
  patch 'cards/edit/:id', to: 'cards#edit'
  get 'cards/delete/:id', to: 'cards#delete'

  get 'people/find'
  post 'people/find'
  get 'people/index'
  get 'people/', to:'people#index'
  get 'people/add'
  post 'people/add', to: 'people#create'
  get 'people/edit/:id', to: 'people#edit'
  post 'people/edit/:id', to: 'people#update'
  patch'people/edit/:id', to: 'people#update'
  get 'people/delete/:id', to: 'people#delete'
  get 'people/:id', to: 'people#show'

  get 'dengonban/index', to: 'dengonban#index'
  post 'dengonban', to: 'dengonban#index'
  get 'dengonban/index'
  post 'dengonban/index'

  get 'helo/index'
  get 'helo', to: 'helo#index'
  post 'helo', to: 'helo#inddex'
  post 'helo/index'
  get 'helo/login_check'
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :content, :name, presence: {message: 'は、必須項目です。'}
end

app/models/blogconfig.rb
class Blogconfig < ApplicationRecord
  validates :title, :stylename, presence: {message: 'は、必須項目です。'}
end

app/models/bloggenre.rb
class Bloggenre < ApplicationRecord
  has_many :blogpost

  validates :name, presence: {message: 'は、必須項目です。'}
end

app/models/blogpost.rb
class Blogpost < ApplicationRecord
  belongs_to :bloggenre

  validates :title, :content, presence: {message: 'は、必須項目です。'}
end

app/models/board_message.rb
class BoardMessage < ApplicationRecord
  belongs_to :board_user

  validates :content, presence: {message: 'は、必須項目です。'}
end

app/models/board_user.rb
class BoardUser < ApplicationRecord
  belongs_to :account
  has_many :board_message

  validates :nickname, presence: {message: 'は、必須項目です。'}
end

app/models/card.rb
class Card < ApplicationRecord
end

app/models/data_page.rb
class DataPage < ApplicationRecord
end

app/models/email_validator.rb
class EmailValidator < AciveModel:EachValidator

  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || "is not an email")
    end
  end

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :person

  validates :message, presence: {message: 'を書いてください。'}
end

app/models/mycontact.rb
class Mycontact < ApplicationRecord
  validates :name, presence: {message: 'は、必須項目です。'}
  validates :age, numericality: {message: 'は、数字で入力ください。'}
  validates :nationality, inclusion: {in: [true, false], message: 'は、真偽値です。'}
end

app/models/person.rb
class Person < ApplicationRecord
     has_many :message

     validates :new, presence:{ message: 'は、必須項目です。'}
     validates :age, numericality: { message: 'は、数字で入力してください。'}
     # validates :mail, email: { message: 'は、メールアドレスではありません。'}
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answer

  validates :content, :name, presence: {message: 'は、必須項目です。'}
end

app/models/questionary.rb
class Questionary < ApplicationRecord
  has_many :questionary_item
  has_many :questionary_result

  validates :title, :description, :deadline, presence: {message:'は、必須項目です。'}
end

app/controllers/data_pages_controller.rb
class DataPagesController < ApplicationController
  before_action :set_data_page, only: %i[ show edit update destroy ]

  # GET /data_pages or /data_pages.json
  def index
    @data_pages = DataPage.page params[:page]
  end

  # GET /data_pages/1 or /data_pages/1.json
  def show
  end

  # GET /data_pages/new
  def new
    @data_page = DataPage.new
  end

  # GET /data_pages/1/edit
  def edit
  end

  # POST /data_pages or /data_pages.json
  def create
    @data_page = DataPage.new(data_page_params)

    respond_to do |format|
      if @data_page.save
        format.html { redirect_to @data_page, notice: "Data page was successfully created." }
        format.json { render :show, status: :created, location: @data_page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @data_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /data_pages/1 or /data_pages/1.json
  def update
    respond_to do |format|
      if @data_page.update(data_page_params)
        format.html { redirect_to @data_page, notice: "Data page was successfully updated." }
        format.json { render :show, status: :ok, location: @data_page }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @data_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data_pages/1 or /data_pages/1.json
  def destroy
    @data_page.destroy
    respond_to do |format|
      format.html { redirect_to data_pages_url, notice: "Data page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_data_page
      @data_page = DataPage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def data_page_params
      params.require(:data_page).permit(:data)
    end
end

app/helpers/ajax_helper.rb
module AjaxHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/data_pages_helper.rb
module DataPagesHelper
end

app/helpers/helo_helper.rb
module HeloHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/data_pages/_form.html.erb
<%= form_with(model: data_page, local: true) do |form| %>
  <% if data_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(data_page.errors.count, "error") %> prohibited this data_page from being saved:</h2>

      <ul>
      <% data_page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :data %>
    <%= form.text_area :data %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/data_pages/edit.html.erb
<h1>Editing Data Page</h1>

<%= render 'form', data_page: @data_page %>

<%= link_to 'Show', @data_page %> |
<%= link_to 'Back', data_pages_path %>

app/views/data_pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Data Pages</h1>

<div><%= page_entries_info @data_pages %></div>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Data</th>
      <th>Created at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @data_pages.each do |data_page| %>
      <tr>
        <td><%= data_page.id %></td>
        <td><%= data_page.data %></td>
        <td><%= data_page.created_at %></td>
        <td><%= link_to 'Show', data_page %></td>
        <td><%= link_to 'Edit', edit_data_page_path(data_page) %></td>
        <td><%= link_to 'Destroy', data_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div><%= paginate @data_pages %></div>
<br>
<%= link_to 'New Data Page', new_data_page_path %>

app/views/data_pages/new.html.erb
<h1>New Data Page</h1>

<%= render 'form', data_page: @data_page %>

<%= link_to 'Back', data_pages_path %>

app/views/data_pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @data_page.data %>
</p>

<%= link_to 'Edit', edit_data_page_path(@data_page) %> |
<%= link_to 'Back', data_pages_path %>